interface HTMLElement : Element {
    // dynamic markup insertion
    attribute DOMString innerHTML;
    attribute DOMString outerHTML;
    void insertAdjacentHTML(in DOMString position, in DOMString text);

    // metadata attributes
    attribute DOMString id;
    attribute DOMString title;
    attribute DOMString lang;
    attribute DOMString dir;
    attribute DOMString className;
    readonly attribute DOMTokenList classList;
    readonly attribute DOMStringMap dataset;

    // microdata 
    attribute boolean itemScope;
    attribute DOMString itemType;
    attribute DOMString itemId;
    [PutForwards=value] readonly attribute DOMSettableTokenList itemRef;
    [PutForwards=value] readonly attribute DOMSettableTokenList itemProp;
    readonly attribute HTMLPropertiesCollection properties;
    attribute any itemValue;

    // user interaction
    attribute boolean hidden;
    void click();
    attribute unsigned long tabIndex;
    void focus();
    void blur();
    attribute DOMString accessKey;
    readonly attribute DOMString accessKeyLabel;
    attribute boolean draggable;
    [PutForwards=value] readonly attribute DOMSettableTokenList dropzone;
    attribute DOMString contentEditable;
    readonly attribute boolean isContentEditable;
    attribute HTMLMenuElement? contextMenu;
    attribute boolean spellcheck;

    // command API
    readonly attribute DOMString? commandType;
    readonly attribute DOMString? commandLabel;
    readonly attribute DOMString? commandIcon;
    readonly attribute boolean? commandHidden;
    readonly attribute boolean? commandDisabled;
    readonly attribute boolean? commandChecked;

    // styling
    readonly attribute CSSStyleDeclaration style;

    // event handler IDL attributes
    attribute Function? onabort;
    attribute Function? onblur;
    attribute Function? oncanplay;
    attribute Function? oncanplaythrough;
    attribute Function? onchange;
    attribute Function? onclick;
    attribute Function? oncontextmenu;
    attribute Function? oncuechange;
    attribute Function? ondblclick;
    attribute Function? ondrag;
    attribute Function? ondragend;
    attribute Function? ondragenter;
    attribute Function? ondragleave;
    attribute Function? ondragover;
    attribute Function? ondragstart;
    attribute Function? ondrop;
    attribute Function? ondurationchange;
    attribute Function? onemptied;
    attribute Function? onended;
    attribute Function? onerror;
    attribute Function? onfocus;
    attribute Function? oninput;
    attribute Function? oninvalid;
    attribute Function? onkeydown;
    attribute Function? onkeypress;
    attribute Function? onkeyup;
    attribute Function? onload;
    attribute Function? onloadeddata;
    attribute Function? onloadedmetadata;
    attribute Function? onloadstart;
    attribute Function? onmousedown;
    attribute Function? onmousemove;
    attribute Function? onmouseout;
    attribute Function? onmouseover;
    attribute Function? onmouseup;
    attribute Function? onmousewheel;
    attribute Function? onpause;
    attribute Function? onplay;
    attribute Function? onplaying;
    attribute Function? onprogress;
    attribute Function? onratechange;
    attribute Function? onreadystatechange;
    attribute Function? onreset;
    attribute Function? onscroll;
    attribute Function? onseeked;
    attribute Function? onseeking;
    attribute Function? onselect;
    attribute Function? onshow;
    attribute Function? onstalled;
    attribute Function? onsubmit;
    attribute Function? onsuspend;
    attribute Function? ontimeupdate;
    attribute Function? onvolumechange;
    attribute Function? onwaiting;
};

interface HTMLUnknownElement : HTMLElement { };

